export const seedPosts = [
  {
    title: "Guía completa de pentesting para empresas en 2025",
    slug: { current: "guia-completa-pentesting-empresas-2025" },
    excerpt: "Descubre qué es un pentest, los tipos que existen y cómo elegir el adecuado para proteger tu empresa de ciberataques.",
    categoryName: "Pentesting",
    authorName: "Carlos Méndez",
    readingTime: 12,
    publishedAt: "2025-03-15T10:00:00Z",
    bodyOutline: [
      { heading: "¿Qué es un pentest y por qué lo necesitas?", summary: "Definición de prueba de penetración, diferencia con escaneo de vulnerabilidades y por qué es esencial para cualquier empresa." },
      { heading: "Tipos de pentesting: caja negra, gris y blanca", summary: "Explicación de los tres enfoques principales, cuándo usar cada uno y sus ventajas e inconvenientes." },
      { heading: "Fases de un pentest profesional", summary: "Reconocimiento, escaneo, explotación, post-explotación e informe. Detalle de cada etapa." },
      { heading: "Cómo elegir un proveedor de pentesting en España", summary: "Certificaciones clave (OSCP, CEH, CREST), preguntas que hacer al proveedor y señales de alerta." },
      { heading: "Frecuencia y presupuesto recomendado", summary: "Cada cuánto realizar un pentest según el sector y cómo justificar la inversión ante dirección." },
    ],
  },
  {
    title: "NIS2 y ENS: lo que tu empresa debe saber en 2025",
    slug: { current: "nis2-ens-normativa-ciberseguridad-2025" },
    excerpt: "La directiva NIS2 y el ENS imponen nuevas obligaciones de ciberseguridad. Te explicamos cómo cumplir sin complicaciones.",
    categoryName: "Normativa",
    authorName: "Laura Fernández",
    readingTime: 10,
    publishedAt: "2025-02-20T09:00:00Z",
    bodyOutline: [
      { heading: "¿Qué es la directiva NIS2?", summary: "Origen, ámbito de aplicación y diferencias con la NIS1. Sectores afectados en España." },
      { heading: "Esquema Nacional de Seguridad (ENS) actualizado", summary: "Principales cambios del RD 311/2022, niveles de seguridad y categorización de sistemas." },
      { heading: "Obligaciones concretas para las empresas", summary: "Gestión de riesgos, notificación de incidentes, cadena de suministro y gobernanza." },
      { heading: "Sanciones por incumplimiento", summary: "Multas previstas en NIS2, responsabilidad de los directivos y plazos de transposición." },
      { heading: "Plan de acción paso a paso", summary: "Checklist práctico para alcanzar el cumplimiento: gap analysis, políticas, formación y auditoría." },
    ],
  },
  {
    title: "Las 10 vulnerabilidades web más explotadas en España",
    slug: { current: "vulnerabilidades-web-mas-explotadas-espana" },
    excerpt: "Analizamos las vulnerabilidades que más detectamos en auditorías a empresas españolas y cómo mitigarlas.",
    categoryName: "Vulnerabilidades",
    authorName: "Carlos Méndez",
    readingTime: 8,
    publishedAt: "2025-01-10T08:00:00Z",
    bodyOutline: [
      { heading: "OWASP Top 10 y el panorama español", summary: "Cómo se compara el ranking global con lo que vemos en auditorías locales." },
      { heading: "Inyección SQL y XSS: siguen liderando", summary: "Casos reales anonimizados, impacto y parches recomendados." },
      { heading: "Fallos de autenticación y gestión de sesiones", summary: "Errores comunes en implementaciones de login, tokens JWT y sesiones sin expiración." },
      { heading: "SSRF y deserialización insegura", summary: "Vulnerabilidades avanzadas que afectan a APIs modernas y microservicios." },
      { heading: "Recomendaciones de mitigación prioritaria", summary: "WAF, validación de entrada, headers de seguridad y ciclo de desarrollo seguro (SSDLC)." },
    ],
  },
];
